export enum MessageKey {
	EDIT = 'wikibase-edit',
	PUBLISH = 'wikibase-publish',
	CANCEL = 'wikibase-cancel',
	ALIAS_SEPARATOR = 'wikibase-aliases-separator',
	ALL_LANGUAGES = 'wikibase-entitytermsforlanguagelistview-more',
	FEWER_LANGUAGES = 'wikibase-entitytermsforlanguagelistview-less',
	IN_MORE_LANGUAGES = 'wikibase-entitytermsview-entitytermsforlanguagelistview-toggler',
	MISSING_LABEL = 'wikibase-label-empty',
	MISSING_DESCRIPTION = 'wikibase-description-empty',
	PLACEHOLDER_EDIT_LABEL = 'wikibase-label-edit-placeholder',
	PLACEHOLDER_EDIT_DESCRIPTION = 'wikibase-description-edit-placeholder',
	PLACEHOLDER_EDIT_ALIAS = 'wikibase-alias-edit-placeholder',
	EDIT_WARNING_HEADING = 'wikibase-anonymouseditwarning-heading',
	EDIT_WARNING_MESSAGE = 'wikibase-anonymouseditwarning-message',
	EDIT_WARNING_DISMISS_BUTTON = 'wikibase-anonymouseditwarning-dismiss-button',
	EDIT_WARNING_DISMISS_PERSIST = 'wikibase-anonymouseditwarning-dismiss-persist',
	LOGIN = 'pt-login',
	CREATE_ACCOUNT = 'pt-createaccount',
	LICENSE_AGREEMENT_ACCEPT_PERSIST = 'wikibase-shortcopyrightwarning-accept-persist',
	LICENSE_HEADER = 'wikibase-shortcopyrightwarning-heading',
	SAVE_ERROR_HEADING = 'wikibase-entity-save-error-heading',
	SAVE_ERROR_MESSAGE = 'wikibase-entity-save-error-message',
}
